[tool.poetry]
name = "pan-globalprotect-okta"
version = "0.1.0"
description = ""
authors = ["Taylor Dean <taylor@makeshift.dev>"]

[tool.poetry.dependencies]
python = "^3.7"
lxml = "^4.5.0"
requests = "^2.22.0"
python-gnupg = "^0.4.5"
pre-commit = "^2.9.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
